### ISSUE TITLE
[Windows10] koaton new throws "no such file or director"

### ISSUE THREAD

**Issue by MilkyWayJoe** [gerard2p/koaton-cli#1]
Hi,

First of all, thanks for creating this project. It's a hug effort and I have been looking into it.

I am trying to test the cli. I am on Windows at the moment, and I ran this:
`PS F:\MilkyWayJoe\the-thing\server> koaton new simple-api`

And the following happened:
```
koaton-cli version 0.0.0

   create: simple-api/ember
Error: ENOENT: no such file or directory, open 'C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cl
i\templates\app.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.render (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\lib\utils\render.js:15:1
5)
    at setupInit (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\lib\commands\new.js:28:8)
    at next (native)
    at onFulfilled (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\co\index.js:6
5:19)
    at tryCatcher (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\bluebird\js\re
lease\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node
_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\bl
uebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\b
luebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\b
luebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\bluebird
\js\release\promise.js:638:18)
    at Promise._resolveCallback (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\
bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node
_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Users\THIAGO~1\AppData\Roaming\nvm\v6.9.0\node_modules\koaton-cli\node_modules\bl
uebird\js\release\promise.js:569:18)
PS F:\MilkyWayJoe\the-thing\server>
```
I'm on node 6.9.0
Please help :)

I'll try a non-windows environment in a bit

**Comment by gerard2p** [comment]
Hello,
Sorry for my late response, I'm actually working to release a 1.1.0 update, but I'm having some problem with some tests that involve nginx, I suggest you to wath the repo so you can receive updates, soon I will make a versión 2 that will basically will be ready to work with koa 2 and will have all dependecies updated.

I've a lot of plans for this project, so if you have any problem, suggestion, complain, pull request, feel free to do it, I'll be happy to check any of them.
